/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ReservierenRouteImport } from './routes/reservieren'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GutscheinDankeRouteImport } from './routes/gutschein-danke'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DinnerRouteImport } from './routes/dinner'
import { Route as BrunchRouteImport } from './routes/brunch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationCancelTokenRouteImport } from './routes/reservation-cancel.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservierenRoute = ReservierenRouteImport.update({
  id: '/reservieren',
  path: '/reservieren',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GutscheinDankeRoute = GutscheinDankeRouteImport.update({
  id: '/gutschein-danke',
  path: '/gutschein-danke',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DinnerRoute = DinnerRouteImport.update({
  id: '/dinner',
  path: '/dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const BrunchRoute = BrunchRouteImport.update({
  id: '/brunch',
  path: '/brunch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationCancelTokenRoute = ReservationCancelTokenRouteImport.update({
  id: '/reservation-cancel/$token',
  path: '/reservation-cancel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brunch': typeof BrunchRoute
  '/dinner': typeof DinnerRoute
  '/events': typeof EventsRoute
  '/gutschein-danke': typeof GutscheinDankeRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/reservation-cancel/$token': typeof ReservationCancelTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brunch': typeof BrunchRoute
  '/dinner': typeof DinnerRoute
  '/events': typeof EventsRoute
  '/gutschein-danke': typeof GutscheinDankeRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/reservation-cancel/$token': typeof ReservationCancelTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/brunch': typeof BrunchRoute
  '/dinner': typeof DinnerRoute
  '/events': typeof EventsRoute
  '/gutschein-danke': typeof GutscheinDankeRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/reservation-cancel/$token': typeof ReservationCancelTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brunch'
    | '/dinner'
    | '/events'
    | '/gutschein-danke'
    | '/kontakt'
    | '/reservieren'
    | '/ueber-uns'
    | '/admin'
    | '/reservation-cancel/$token'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brunch'
    | '/dinner'
    | '/events'
    | '/gutschein-danke'
    | '/kontakt'
    | '/reservieren'
    | '/ueber-uns'
    | '/admin'
    | '/reservation-cancel/$token'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brunch'
    | '/dinner'
    | '/events'
    | '/gutschein-danke'
    | '/kontakt'
    | '/reservieren'
    | '/ueber-uns'
    | '/_authenticated/admin'
    | '/reservation-cancel/$token'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrunchRoute: typeof BrunchRoute
  DinnerRoute: typeof DinnerRoute
  EventsRoute: typeof EventsRoute
  GutscheinDankeRoute: typeof GutscheinDankeRoute
  KontaktRoute: typeof KontaktRoute
  ReservierenRoute: typeof ReservierenRoute
  UeberUnsRoute: typeof UeberUnsRoute
  ReservationCancelTokenRoute: typeof ReservationCancelTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservieren': {
      id: '/reservieren'
      path: '/reservieren'
      fullPath: '/reservieren'
      preLoaderRoute: typeof ReservierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gutschein-danke': {
      id: '/gutschein-danke'
      path: '/gutschein-danke'
      fullPath: '/gutschein-danke'
      preLoaderRoute: typeof GutscheinDankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dinner': {
      id: '/dinner'
      path: '/dinner'
      fullPath: '/dinner'
      preLoaderRoute: typeof DinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brunch': {
      id: '/brunch'
      path: '/brunch'
      fullPath: '/brunch'
      preLoaderRoute: typeof BrunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation-cancel/$token': {
      id: '/reservation-cancel/$token'
      path: '/reservation-cancel/$token'
      fullPath: '/reservation-cancel/$token'
      preLoaderRoute: typeof ReservationCancelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrunchRoute: BrunchRoute,
  DinnerRoute: DinnerRoute,
  EventsRoute: EventsRoute,
  GutscheinDankeRoute: GutscheinDankeRoute,
  KontaktRoute: KontaktRoute,
  ReservierenRoute: ReservierenRoute,
  UeberUnsRoute: UeberUnsRoute,
  ReservationCancelTokenRoute: ReservationCancelTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
