/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as ReservierenRouteImport } from './routes/reservieren'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservierenRoute = ReservierenRouteImport.update({
  id: '/reservieren',
  path: '/reservieren',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/reservieren': typeof ReservierenRoute
  '/ueber-uns': typeof UeberUnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/reservieren' | '/ueber-uns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/reservieren' | '/ueber-uns'
  id: '__root__' | '/' | '/kontakt' | '/reservieren' | '/ueber-uns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  ReservierenRoute: typeof ReservierenRoute
  UeberUnsRoute: typeof UeberUnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservieren': {
      id: '/reservieren'
      path: '/reservieren'
      fullPath: '/reservieren'
      preLoaderRoute: typeof ReservierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  ReservierenRoute: ReservierenRoute,
  UeberUnsRoute: UeberUnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
